name: (called workflow) Build, Test, and Publish

on:
  workflow_call:
    inputs:
      languages:
        description: "The languages to build images for"
        required: true
        default: "[]"
        type: string
      test:
        description: "Whether to run tests"
        default: true
        type: boolean
      publish:
        description: "Whether to publish images"
        default: false
        type: boolean

jobs:
  generate-composite-dockerfile:
    name: 📝 Dockerfile.composite
    runs-on: ubuntu-latest
    steps:
      -
        name: 🛒 Checkout
        uses: actions/checkout@master

      -
        name: 📝 Dockerfile.composite
        shell: bash
        run: |
          make composite-dockerfile > /dev/null

      -
        name: ⬆️ Dockerfile.composite
        uses: actions/upload-artifact@v4
        with:
          name: composite-dockerfile
          path: Dockerfile.composite
          retention-days: 1

  build-test:
    name:  ${{ matrix.language }} (linux/amd64)
    runs-on: ubuntu-latest
    if: ${{ inputs.test }}
    needs:
      - generate-composite-dockerfile
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJSON(inputs.languages) }}

    steps:
      -
        name: 🛒 Checkout
        uses: actions/checkout@master

      -
        name: ⬇️ Dockerfile.composite
        uses: actions/download-artifact@v4
        with:
          name: composite-dockerfile

      -
        name: 🧪 Test
        uses: ./.github/actions/build-test-publish
        continue-on-error: false
        with:
          display-as: ${{ matrix.language }}
          dockerfile: Dockerfile.composite
          docker-image: 100hellos/${{ matrix.language }}
          docker-build-target: o100hellos_${{ matrix.language }}
          platforms: linux/amd64

  publish:
    name: 🚀 ${{ matrix.language }} (linux/amd64)
    runs-on: ubuntu-latest
    if: ${{ inputs.publish }}
    needs:
      - build-test
      - generate-composite-dockerfile
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJSON(inputs.languages) }}

    steps:
      -
        name: 🛒 Checkout
        uses: actions/checkout@master

      -
        name: ⬇️ Dockerfile.composite
        uses: actions/download-artifact@v4
        with:
          name: composite-dockerfile

      -
        name: Generate Documentation
        id: has-docs
        shell: bash
        run: |
          ./.github/bin/generate-overview-readme.sh ${{ matrix.language }}

      -
        name: 🎬 Publish
        uses: ./.github/actions/build-test-publish
        continue-on-error: true
        with:
          display-as: ${{ matrix.language }}
          dockerfile: Dockerfile.composite
          docker-image: 100hellos/${{ matrix.language }}
          docker-build-target: o100hellos_${{ matrix.language }}
          platforms: linux/amd64

          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-description: "\"Hello World!\" Written in ${{ matrix.language }}"
          dockerhub-readme: ./${{ matrix.language }}/README-Generated.md

          test: ${{ inputs.test }}
          publish: ${{ inputs.publish }}
