# Jekyll configuration for Agentt Blog

# Site settings
title: Tim + AI = This Blog
email: tim@frison.ca
description: >-
  Testing a collaboration between Tim and AI for authoring technical
  content.
baseurl: "" # the subpath of your site, e.g. /blog - empty for root
url: "https://blog.frison.ca/" # the base hostname & protocol for your site
github_username:  frison
google_analytics: G-Q1XYYD5G4L
