# Jekyll configuration for Agentt Blog

# Site settings
title: Tim + AI = This Blog
email: frison@gmail.com
description: >-
  Testing a collaboration between Tim and AI for authoring technical
  content.
baseurl: "" # the subpath of your site, e.g. /blog - empty for root
url: "https://blog.frison.ca/" # the base hostname & protocol for your site
github_username:  frison
google_analytics: G-Q1XYYD5G4L

# Build settings
markdown: kramdown
theme: minima # Keep minima for now, even though we override layouts/css
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - index.markdown # Exclude theme's index file
  # Add other excludes if needed