listenAddress: ":8080"

entityTypes:
  - name: "behavior"
    description: "Defines rules, constraints, or preferred practices for agent operation."
    requiredFields: ["id", "title", "tier", "priority", "tags"] # Added back priority and tags

  - name: "recipe"
    description: "Provides step-by-step instructions or procedures for specific tasks."
    requiredFields: ["id", "title", "priority", "tags"] # Added back priority and tags

backends:
  - name: "local_primary"
    type: localfs
    settings:
      rootDir: "../"
      entityLocations:
        behavior: "behaviors/**/*.bhv"
        recipe: "recipes/**/*.rcp"

  - name: "user_primary"
    type: localfs
    settings:
      rootDir: "~/.agentt"
      entityLocations:
        behavior: "**/*.bhv"
        recipe: "**/*.rcp"
