listenAddress: ":8080"

# llmGuidanceFile: "llm_guidance.txt" # REMOVED - Now embedded

entityTypes:
  - name: "behavior"
    description: "Defines behavioral directives (MUSTs and SHOULDs) for the agent."
    pathGlob: "../behavior/**/*.bhv" # Path relative to this file
    fileExtensionHint: ".bhv"
    requiredFrontMatter:
      - "title"
      - "priority"
      - "description"
      - "tags"
      # Tier (must/should) will be inferred from path later

  - name: "recipe"
    description: "Provides procedural steps for specific tasks."
    pathGlob: "../cookbook/**/*.rcp" # Path relative to this file
    fileExtensionHint: ".rcp"
    requiredFrontMatter:
      - "id"
      - "title"
      - "priority"
      - "description"
      - "tags"

  # Add persona here later, e.g.:
  # - name: "persona"
  #   description: "Defines agent personas or modes of operation."
  #   pathGlob: ".agent/personas/**/*.prs"
  #   requiredFrontMatter:
  #     - "id"
  #     - "name"
  #     - "tags"

  # Add reflex manifest here later, e.g.:
  # - name: "reflex"
  #   description: "Manifest describing a reflex (containerized tool)."
  #   pathGlob: ".agent/reflexes/**/*.yaml"
  #   requiredFrontMatter:
  #     - "id"
  #     - "image"
  #     - "tags"

backend:
  type: localfs
  rootDir: "."